FROM mcr.microsoft.com/powershell

SHELL ["/bin/sh", "-c"]
RUN mkdir DDNS && apt update && apt install -y cron
COPY ./cloudflare-ddns.ps1 /DDNS/cloudflare-ddns.ps1
COPY ./crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab && touch /var/log/cron.log
CMD  sed -i "s/CRON_PLACEHOLDER/$CRON/g" /etc/cron.d/crontab && cron /etc/cron.d/crontab && tail -f /var/log/cron.log
